---
title: "Extracting sunbeams from cucumbers: Reproducibility as a necessity for the future of archaeological science"
format: html
bibliography: references.bib
---

```{=html}
<!-- 

authoritative, agenda-setting or hypothesis-setting papers, rather than descriptive compilations of the literature.

have the vision and authority to guide the next generation of archaeological science research

cross-ref Vaiglova 2025 this issue

-->
```

## Introduction

In their paper celebrating the 40th anniversary of this journal Torrence et al [-@torrenceFortyYearsStill2015] noted that reproducibility was an issue important to the reputation and sustainability of the discipline, and necessary for archaeological science to behave like a science. As part of the celebration of the 50th anniversary, and of Torrence's leadership of the journal, my contribution revisits these topics of archaeology's status as a science, this journal's place in the landscape of archaeological science, and how the journal has responded to a growing recognition of the importance of reproducibility. I first present bibliometric evidence of the position of archaeology as a whole, and this journal in particular, in the hierarchy of the sciences. Next I report on the journal's progress in supporting reproducible research, and my work doing a new kind of peer review for JAS, one that evaluates the computational reproducibilty of the research submitted for publication.

The question of archaeology's status as a science usually comes up in the context of what the discipline should or should not be. One of the first landmarks in tackling this question is the debate published by *Antiquity* between classical archaeologist Jacquetta Hawkes and palaeoanthropologist Glynn Isaac. @hawkesProperStudyMankind1968, advocating a humanistic archaeology, was concerned that scientific approaches to archaeology were causing researchers to be "swamped by a vast accumulation of insignificant, disparate facts, like a terrible tide of mud, quite beyond the capacity of any man to contain and mould into historical form". More optimistic about the integration of science and archaeology, @isaacWhitherArchaeology1971 counters that "New levels of precision in presenting data and in interpreting them can surely lead to briefer and more interesting technical reports as well as providing the basis for more lively literary portrayals of what happened in prehistory. Expanding on Isaac's perspective, @binford1962archaeology argued that archaeology should operate as a science after the model proposed by philosopher Carl Hempel, which prescribed hypothesis-driven approaches, leading to generalizable laws of human behavior. Counter-arguments came from numerous directions, notably @hodder1985postprocessual who rejected the quest for generalisations and instead argued that archaeology should be subjective and reflective, focussed on symbolic and relational meanings of material culture and the historical particularity of past human cultures. These debates, and the many more similar ones summarised by @martinon-torresArchaeologicalTheoriesArchaeological2013, have become a genre in archaeological writing that can be characterized as mostly based on personal observations, microscopic dissections of a handful of cherry-picked case studies of good or bad practice, and discussion of various philosophers and sociologists.

What has been missing from these debates is a macroscopic observation of what the majority of archaeologists are actually doing, and an empirical comparison to a broad spectrum of relatively harder and softer disciplines. At the 'hard' end of the spectrum (e.g. physics and chemistry), scholars more typically share an established set of theories, facts, and methods, facilitating fairly rapid agreement on the validity and significance of new results. At the 'soft' end of the spectrum (e.g. economics and psychology), the theories, facts, and methods on which there is widespread consensus is smaller, and agreement is slower and less frequently reached about the significance of new findings and the continuing relevance of previous work. Hardness and softness is a controversial distinction, in part because it is often used to imply a rank order of disciplines that encodes legitimacy, productivity, perceived value to society, and worthiness of funding [@DifferentAgenda2012; @coleHierarchySciences1983]. However, independent of these value judgments, empirical analysis of scholarly articles does indicate a spectrum of variation in practice linked to differing degrees of consensus in a discipline, for example in approaches to data visualisation [@clevelandGraphsScientificPublications1984; @smithScientificGraphsHierarchy2000]. Similarly, quantitative analysis of the frequency of positive results (ie. full or partial support for a research hypothesis) in publications is significantly correlated with hardness, consistent with a model where researchers in harder fields more readily accept any result their research produces, while those in softer fields have more freedom to choose which theories and hypotheses to test and how to interpret results [@PositiveResultsIncrease]. The hard-soft spectrum is also evident in surveys of how researchers view their own work relative to those in other fields [@biglanCharacteristicsSubjectMatter1973].

Here I take a bibliometric approach to objectively quantify the relative hardness or softness of archaeology to evaluate its status as a science, and the place of this journal in the discipline. For a large sample of peer-reviewed journal articles, I quantify the number of authors, length of article, relative title length, number of cited references, age of references, and diversity of references. These parameters are useful because of how they signify consensus in a research community. A larger number of authors on a paper reflects collaboration of people with specialized roles, each of whom has the ability to study a part of the problem with high accuracy and detail [@zuckerman1972age]. Harder disciplines tend to have higher average numbers of authors on papers. In low-consensus, or softer, fields, papers must be longer to present justification, nuance and contextualization of results. I used page numbers to measure article length. Similarly, the number of cited references will typically be higher in low-consensus disciplines where relatively fewer claims are taken for granted and thus need citations for support, relative to harder fields [@skilton2006comparative]. The age of works cited has long been used as a measure of a field's hardness [@moed1998new; @bornerAtlasScience2010], based on the assumption that harder fields assimilate new results more rapidly that softer fields [@price1970citation]. I calculated the Price index for each article which is the proportion of citated worked published in the five years preceding the paper.

n an ideal science, scholars share a common background of established theories, facts and methods. This allows them to agree (usually after debate and further evidence) on the validity and significance of a new research finding, making it the basis for further theorizing and research. Harder sciences are hypothesised to come closer to this ideal. Moving towards “softer” fields, this consensus becomes less likely to be reached, the common background shrinks and fractures, and so data become less able to “speak for themselves” [\[](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0066938#pone.0066938-Fanelli1)

Computational reproducibilty has become central to archaeology's status a science, especially as the definition and practice of science shifts over time. Computers have become an essential field and laboratory instrument for almost all of us, so we should document how we change our data as it flows through silicon just as carefully as we document the operating parameters of a mass spectrometer or other laboratory instrument. In making the case for reproducibilty as a core value in archaeological science

In recent years the Journal of Archaeological Science has been one of a number of archaeology journals that introduced an unusual new kind of peer review, one that evaluates the computational reproducibilty of the research submitted for publication. This journal was among the first of these and is currently by far the most active in conducting these reviews. In this article I reflect on how this new kind of review came about, why it is important for the future of archaeological science, and offer suggestions for prospective authors based on my experience as a reproducibilty reviewer for this journal on how we can ensure archaeological science remains worthy of the name.

My motivation is the view that It is customary in significant round-number anniversary
