---
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)

```

# Extracting sunbeams from cucumbers: Computational reproducibility is essential for archaeological science

This repository contains the data and code for my paper that has been submitted to the _Journal of Archaeological Science_. Earlier versions were presented at the University of Cambridge [(2019)](https://github.com/benmarwick/March-2019-Cambridge-Big-Data-Archaeology) and New York University [(2025)](https://github.com/benmarwick/nyu-2025-workshop). A pre-print of the paper is online here and may be cited as follows:

> Marwick, B. (2025). Extracting sunbeams from cucumbers: Computational reproducibility is essential for archaeological science. Pre-print hosted at SocArXiv. Accessed 21 February 2025. https://doi.org/10.31235/osf.io/fdhvb_v1 

## Contents

The **analysis** directory contains:

-   [:file_folder: paper](/analysis/paper): Quarto source document for
    manuscript. Includes code to reproduce the figures and tables
    generated by the analysis.
-   [:file_folder: data](/analysis/data): Data used in the analysis.
-   [:file_folder: figures](/analysis/figures): Plots and other
    illustrations

## How to download and run locally in a Docker container

This research compendium includes a [Dockerfile](Dockerfile) that specifies the computational environment used to generate the results presented in the paper. You can recreate this environment, which includes R, RStudio and all necessary R packages, on your computer by following these steps:

1. Install [Docker](https://www.docker.com/get-started/) on your computer 
2. Download the compendium, e.g. from GitHub by clicking on the green `< > Code` button above, then click `Download ZIP`, then unzip on your computer
3. Set your terminal working directory to the compendium, and run `docker build -t wos .` to build the container on your computer, it will take a few minutes and require an internet connection.
4. Run in your terminal `docker run --rm -it -e ROOT=TRUE -e PASSWORD=rstudio -dp 8787:8787 wos` to start the container on your computer
5. Go to http://localhost:8787/ with your browser and enter `rstudio` in both fields to start RStudio in your browser, running in the Docker container with all the required depedencies installed
6. In RStudio, run `rstudioapi::openProject("/home/rstudio/web-of-science-archaeology")` to open the compendium's project
7. Run ` rmarkdown::render("analysis/paper/paper.qmd", output_dir='/tmp')` to render the Quarto document that is the manuscript submitted for publication
8. After the code has executed, view the rendered output document by running `browseURL("/tmp/paper.html")`
8. When finished, to delete the Docker container from your computer, run this in the terminal `docker ps -aq | xargs docker stop | xargs docker rm`

### Licenses

**Text and figures :**
[CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)

**Code :** See the [LICENSE](LICENSE.md) file

**Data :** [CC-0](http://creativecommons.org/publicdomain/zero/1.0/)
attribution requested in reuse

### Contributions

We welcome contributions from everyone. Before you get started, please
see our [contributor guidelines](CONTRIBUTING.md). Please note that this
project is released with a [Contributor Code of Conduct](CONDUCT.md). By
participating in this project you agree to abide by its terms.
